### ISSUE TITLE
ESPHost does not work properly when building esp-hosted-fg from master.

### ISSUE THREAD

**Issue by PontusO** [Networking-for-Arduino/ESPHost#5]
Checking the source there seem to be a misalignment in protobuf requests responses as well as in the control messages between the latest on master (0.0.6?) and the tag release/fg-v0.0.5.

**Comment by JAndrassy** [comment]
yes. you have to use sources for the 0.0.5 release tag.

**Comment by PontusO** [comment]
Aah, but there is no support for the C6 in 0.0.5 =)

**Comment by JAndrassy** [comment]
the IDF version used in 0.0.5 already supports the C6 so I planed to just add a section for C6 in spi_slave_api.c.
I just don't have a C6 board to try.
what I saw C3 and C6 are very similar.

**Comment by PontusO** [comment]
That might be a good way to start actually. Let me know if you want to send you one of our new boards with a C6 on it.

**Comment by JAndrassy** [comment]
so I made the [firmware](https://github.com/Networking-for-Arduino/ESPHost/tree/main/extras/firmware/Challenger2040WiFiBLE) 
for the C3 for your RP2040 board, but I don't know if it works?

I can prepare a C6 version, but what are the ESP32 pins wired to the RP? are they same on 2040 and 2350 Challenger boards?

**Comment by PontusO** [comment]
I have built new images for both the RP2040 (ESP32C3) and RP2350 (ESP32C6) boards now based on the 0.0.5 release so closing this.

**Comment by JAndrassy** [comment]
do you have BLE over UART working too?

https://github.com/espressif/esp-hosted/tree/master/esp_hosted_fg#152-mcu-host
> With the help of this UART interface, BT/BLE stack can directly interact with BT controller present on ESP bypassing host driver and firmware. ESP Hosted host driver and a firmware plays no role in this communication

**Comment by PontusO** [comment]
Currently no, both wifi and ble are configured as SPI. I'm working on a shim for BLE for the arduino-pico framework and i wanted to make it as similar to the existing solution as possible.
